### ISSUE TITLE
Update to latest version v1.6.109

### ISSUE THREAD

**Issue by baesik** [LeCloutPanda/DebugMode#6]
Mod version: v1.0.7-a
Game version: v1.6.109
Melon loader version: v0.6.1

Issue: Currently getting repeating error messages and would love to try out some fun debug stuff. Would love to see an update. Thanks!

**Comment by LeCloutPanda** [comment]
Sorry for the late response/Lack of updates as I have been busy porting other mods for other games over to a new platform whilst also dealing with life stuff.

But as I tried working on DebugMode but VSMenuModHelper throws a error when I try to make a Tick box detailed in my issue [here](https://github.com/nwfistere/VSMenuModHelper/issues/12#issue-1920869122) so stay tuned for a fix hopefully soon.
