### ISSUE TITLE
Debug Mode No Longer Working In Lasted Vampire Survivors Release

### ISSUE THREAD

**Issue by Bioness-zz** [LeCloutPanda/DebugMode#8]
I understand you're no longer active with Vampire Survivors, I appreciate all the work you have done. Posting this issue just in case there is a chance it could get fixed

Mod version: v1.0.7.2
Game version: v1.12.105 - Release
Melon loader version: v0.6.5 Open-Beta

Issue: Mod no longer works with lasted DLC release

[24-10-31_17-1-36.log](https://github.com/user-attachments/files/17593821/24-10-31_17-1-36.log)

**Comment by LeCloutPanda** [comment]
Hopefully solved with release [v1.0.8](https://github.com/LeCloutPanda/DebugMode/releases/tag/v1.0.8), I will not close this until I am certain it should be working for others.

**Comment by LeCloutPanda** [comment]
Closing this as it is solved and working, thanks for testing it.
