### ISSUE TITLE
Unresponsive as of v1.12.107

### ISSUE THREAD

**Issue by WildTooth** [LeCloutPanda/DebugMode#9]
Mod version: v1.0.8
Game version: v1.12.107 - Release
Melon loader version: v0.6.6

Issue: Nothing seems to be working as intended

Screenshot: Provided the only logoutput recieved.
![image](https://github.com/user-attachments/assets/ba79422d-08bd-4576-b951-c9934a9d4097)

**Comment by LeCloutPanda** [comment]
Can you give me a bit more information then ``Nothing seems to be working as intended`` like are the keybinds not working or what?

**Comment by WildTooth** [comment]
Yes, the keybinds are not working. Sorry for not including this in the initial message.

**Comment by LeCloutPanda** [comment]
Sorry for the late reply I have been busy with Server stuff and other projects but have you trid holding down ``LeftShift`` + ``Key``, I don't state it in the read me but you do have to hold ``LeftShift`` down

**Comment by WildTooth** [comment]
I simply forgot that you needed to hold LeftShift down also.. I have used this before a long time ago, so I did not get the memo ig T-T

**Comment by LeCloutPanda** [comment]
Sorry about that, because there were more stuff added from my initial release I was running out of binds and also to accidently not press one I made it so you have to hold shift. Is the issue resolved? am I clear to close this?

**Comment by WildTooth** [comment]
I'll just close it myself with this comment, thanks for helping out and sorry for the inconvenience 🤣
